spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          # Point to your IdP's issuer. Boot will call /.well-known/openid-configuration
          issuer-uri: ${SECURITY_ISSUER_URI:https://auth.example.com/realms/order-platform}
          # set a custom jwk cache TTL via bean
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
    consumer:
      group-id: api-gateway
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: ${GATEWAY_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
