-- Users (status SMALLINT instead of enabled BOOLEAN)
CREATE TABLE IF NOT EXISTS users (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email          VARCHAR(255) NOT NULL,
    password_hash  VARCHAR(100) NOT NULL,
    status         SMALLINT     NOT NULL DEFAULT 0,  -- 0=ACTIVE, 1=SUSPENDED, 2=DEACTIVATED, 3=LOCKED, 4=PENDING
    username       VARCHAR(100) NOT NULL,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT chk_users_status CHECK (status IN (0,1,2,3,4))
);

-- Case-insensitive uniqueness for login lookups
CREATE UNIQUE INDEX IF NOT EXISTS uq_users_username_ci ON users (lower(username));
CREATE UNIQUE INDEX IF NOT EXISTS uq_users_email_ci    ON users (lower(email));