-- Items per order. Tenant is denormalized for quick scoping.
CREATE TABLE IF NOT EXISTS order_items (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id     VARCHAR(64)   NOT NULL,
    order_id      BIGINT        NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    product_id    UUID          NOT NULL,
    sku           VARCHAR(128)  NOT NULL,
    name          VARCHAR(255)  NULL,
    quantity      INTEGER       NOT NULL CHECK (quantity > 0),
    unit_price    NUMERIC(19,2) NOT NULL CHECK (unit_price >= 0),
    line_total    NUMERIC(19,2) NOT NULL,
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ   NOT NULL DEFAULT now()
);

-- Helpful indexes for reads/updates
CREATE INDEX IF NOT EXISTS idx_order_items_order_tenant ON order_items(order_id, tenant_id);
CREATE INDEX IF NOT EXISTS idx_order_items_order ON order_items(order_id);