-- Enable extensions we’ll rely on
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- orders table (BIGINT PK to match existing OutboxRow.aggregateId: Long)
CREATE TABLE IF NOT EXISTS orders (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id     VARCHAR(64)     NOT NULL,
    user_id       UUID            NOT NULL,
    total_amount  NUMERIC(19,2)   NOT NULL CHECK (total_amount >= 0),
    status        SMALLINT        NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ     NOT NULL DEFAULT now()
    );

-- keep it tenant-friendly
CREATE INDEX IF NOT EXISTS idx_orders_tenant_created_at
    ON orders (tenant_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_orders_status
    ON orders (status);

-- updated_at trigger
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at := now();
RETURN NEW;
END
$$;

DROP TRIGGER IF EXISTS trg_orders_set_updated_at ON orders;
CREATE TRIGGER trg_orders_set_updated_at
    BEFORE UPDATE ON orders
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();