CREATE TABLE IF NOT EXISTS disputes (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        VARCHAR(64)  NOT NULL,
    payment_id       BIGINT       NOT NULL REFERENCES payments(id) ON DELETE CASCADE,

    psp              VARCHAR(64)  NOT NULL,
    psp_dispute_id   VARCHAR(128) NOT NULL,
    reason_code      VARCHAR(64),
    stage            VARCHAR(32)  NOT NULL,
    amount_minor     BIGINT       NOT NULL CHECK (amount_minor >= 0),
    currency_code    CHAR(3)      NOT NULL CHECK (currency_code = upper(currency_code) AND currency_code ~ '^[A-Z]{3}$'),

    opened_at        TIMESTAMPTZ,
    closed_at        TIMESTAMPTZ,

    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT uq_dispute UNIQUE (tenant_id, psp, psp_dispute_id)
);

CREATE INDEX IF NOT EXISTS idx_disputes_payment    ON disputes(payment_id);
CREATE INDEX IF NOT EXISTS idx_disputes_stage      ON disputes(stage);
CREATE INDEX IF NOT EXISTS idx_disputes_opened_at  ON disputes(opened_at);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger WHERE tgname = 'trg_disputes_set_updated_at'
  ) THEN
CREATE TRIGGER trg_disputes_set_updated_at
    BEFORE UPDATE ON disputes
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
END IF;
END $$;
