spring:
  application:
    name: order-service

  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT_ORDER:5430}/${DB_NAME_ORDERS:orders}
    username: ${DB_USER:user}
    password: ${DB_PASS:pass}

  flyway:
    enabled: true
    locations: classpath:db/migration

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: order-service
      auto-offset-reset: earliest

server:
  port: ${ORDER_PORT:8081}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

logging:
  file:
    name: logs/${spring.application.name}.log

  # NEW: Logback rolling‑policy settings
  logback:
    rollingpolicy:
      # how big each file can grow before rolling over
      max‑file‑size: 50MB
      # how many days to keep archived files
      max‑history: 30
      # (optional) total cap on all archives, e.g. 1GB
      total‑size‑cap: 1GB

  # your existing level & pattern config...
  level:
    root: INFO
    com.github.dimitryivaniuta: DEBUG

  pattern:
    console: "[%d{yyyy‑MM‑dd HH:mm:ss.SSS}] [%thread] %-5level %logger{36} ‑ %msg%n"
    file:    "[%d{yyyy‑MM‑dd HH:mm:ss.SSS}] [%thread] %-5level %logger{36} ‑ %msg%n"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html